# Generated by Django 3.2.8 on 2021-11-28 18:29

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('post', ckeditor.fields.RichTextField()),
                ('uploads', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
