# Generated by Django 3.2.8 on 2021-11-28 18:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploads',
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
